USE DataWarehouseAnalytics -- first Execut this line when you work in this query page 

--***********************************************************--
-- Database Exeploration 

-- Sare table dekhna joki database mai hai
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- view any table all columns and their datatype 
SELECT * from INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_products'



--***********************************************************--
--Dimension Exploration 

-- Explore all the Contries our customer come form  
SELECT DISTINCT country from gold.dim_customers

-- Explore all Categories "The major Division"
SELECT 
	DISTINCT category, 
	subcategory, 
	product_name
FROM gold.dim_products
WHERE category IS NOT NULL 
order by 1,2,3

--***********************************************************--
-- Date Exploration

-- Determine the first and last order date and the total duration in months
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales;

-- Find the youngest and oldest customer based on birthdate
SELECT
    MIN(birthdate) AS oldest_birthdate,
    DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers;


--***********************************************************--

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_name) AS total_products FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers;

--***********************************************************--
-- Magnitude Analysis
-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
--***********************************************************--
-- Ranking Top N , Bottom N 
--SELECT COUNT(DISTINCT product_key) from gold.fact_sales;
-- Whcih 5 Product generate the hightest Revenue 
WITH product_revenue AS (
    SELECT 
        p.product_name,
        SUM(f.sales_amount) AS Total_revenue
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p 
        ON f.product_key = p.product_key
    GROUP BY p.product_name
)
SELECT 
    product_name,
    Total_revenue,
    DENSE_RANK() OVER(ORDER BY Total_revenue DESC) AS rnk
    FROM product_revenue;

--***********************************************************--
--***********************************************************--
-- Ranking Top N , Bottom N 
--SELECT COUNT(DISTINCT product_key) from gold.fact_sales;
-- Whcih 5 Product generate the hightest Revenue 
WITH product_revenue AS (
    SELECT 
        p.product_name,
        SUM(f.sales_amount) AS Total_revenue
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p 
        ON f.product_key = p.product_key
    GROUP BY p.product_name
)
SELECT 
    product_name,
    Total_revenue,
    DENSE_RANK() OVER(ORDER BY Total_revenue DESC) AS rnk
    FROM product_revenue;

--***********************************************************--


-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- The 3 customers with the fewest orders placed
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders ;
